In [13]:
import pandas as pd
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import joblib

train_path=os.path.join("..","data","raw","train.csv")
test_path=os.path.join("..","data","raw","test.csv")
df= pd.read_csv(train_path,index_col=0)

In [5]:
df.head(5)

,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,...,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,ID,random_noise
Total a Pagar,,,,,,,,,,,,,,,,,,,,,
558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,1,...,660784,Maybe Tomorrow Payment 10,VLOOKUP Master 9,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2024-10-29,10000000,-0.660448
978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,1,...,189146,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 1,2017-07-08,10000001,0.924510
10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,1,...,103940,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,NaN,Final Excel Warehouse 1,Ctrl Z Series 3,2019-03-19,10000002,-0.258730
856.83,696.61,696.61,160.22,0.0,0.0,0.00,408.167275,9.0,1.0,0,...,512927,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 71,Final Excel Warehouse 1,Ctrl Z Series 3,2018-11-10,10000003,1.448402
1616.10,1488.85,1313.90,302.20,0.0,0.0,174.95,485.401864,33.0,1.0,1,...,122356,Maybe Tomorrow Payment 12,NaN,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2021-11-30,10000004,-1.058890

In [76]:
df.info()

<class 'pandas.DataFrame'>
Index: 6534 entries, 558.11 to 951.71
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total Bruto                     6469 non-null   float64
 1   Total Liquido                   6469 non-null   float64
 2   Total Imp_                      6469 non-null   float64
 3   Total Portes                    6469 non-null   float64
 4   Total Desc_ Global              6469 non-null   float64
 5   Total Desc_ Linha               6469 non-null   float64
 6   Custo                           6469 non-null   float64
 7   N_ Detalhes                     6469 non-null   float64
 8   invoice_count_current_purchase  6469 non-null   float64
 9   repeat_purchase_90d             6534 non-null   int64
 10  days_since_previous_purchase    5673 non-null   float64
 11  customer_tenure_days            6469 non-null   float64
 12  prior_purchase_count            6469 non-null   float64
 13  prior_total_spend               6469 non-null   float64
 14  prior_mean_purchase_value       5672 non-null   float64
 15  prior_std_purchase_value        5421 non-null   float64
 16  prior_min_purchase_value        5866 non-null   float64
 17  prior_max_purchase_value        5866 non-null   float64
 18  prior_mean_gap_days             5226 non-null   float64
 19  prior_std_gap_days              5056 non-null   float64
 20  purchase_count_30d              6469 non-null   float64
 21  spend_30d                       6469 non-null   float64
 22  purchase_count_90d              6469 non-null   float64
 23  spend_90d                       6469 non-null   float64
 24  purchase_count_180d             6469 non-null   float64
 25  spend_180d                      6469 non-null   float64
 26  purchase_count_365d             6469 non-null   float64
 27  spend_365d                      6274 non-null   float64
 28  customer_id                     6534 non-null   int64
 29  payment_type                    6274 non-null   str
 30  salesperson                     6275 non-null   str
 31  commercial_zone                 6469 non-null   str
 32  transport_method                6273 non-null   str
 33  warehouse                       6274 non-null   str
 34  document_series                 6469 non-null   str
 35  purchase_date                   6469 non-null   str
 36  ID                              6534 non-null   int64
 37  random_noise                    6469 non-null   float64
dtypes: float64(28), int64(3), str(7)
memory usage: 1.9 MB

In [77]:
df.describe().round()

,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,...,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,ID,random_noise
count,6469.0,6469.0,6469.0,6469.0,6469.0,6469.0,6469.0,6469.0,6469.0,6534.0,...,6469.0,6469.0,6469.0,6469.0,6469.0,6469.0,6.274000e+03,6534.0,6534.0,6469.0
mean,886.0,773.0,152.0,1.0,0.0,112.0,328.0,22.0,1.0,1.0,...,457.0,2.0,1254.0,3.0,2651.0,7.0,2.396535e+06,506472.0,10003833.0,-0.0
std,1328.0,1136.0,225.0,6.0,5.0,290.0,520.0,28.0,0.0,0.0,...,1191.0,3.0,2348.0,5.0,4020.0,10.0,4.884113e+07,266556.0,2219.0,1.0
min,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.591150e+05,103940.0,10000000.0,-4.0
25%,176.0,154.0,30.0,0.0,0.0,0.0,49.0,4.0,1.0,0.0,...,0.0,0.0,0.0,1.0,149.0,1.0,6.380000e+02,258332.0,10001911.0,-1.0
50%,446.0,390.0,80.0,0.0,0.0,13.0,153.0,11.0,1.0,1.0,...,0.0,1.0,198.0,2.0,1118.0,3.0,2.427000e+03,489625.0,10003824.0,-0.0
75%,1037.0,903.0,185.0,0.0,0.0,92.0,396.0,29.0,1.0,1.0,...,338.0,2.0,1515.0,3.0,3404.0,7.0,7.045000e+03,755628.0,10005760.0,1.0
max,21578.0,18128.0,4169.0,181.0,218.0,4103.0,7427.0,423.0,5.0,1.0,...,22297.0,22.0,30235.0,37.0,49747.0,60.0,1.000000e+09,998870.0,10007674.0,4.0

In [78]:
df["repeat_purchase_90d"].value_counts(normalize=True)*100

repeat_purchase_90d
1    55.922865
0    44.077135
Name: proportion, dtype: float64

In [11]:
(df[df["repeat_purchase_90d"]==1].describe()).round()

,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,...,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,ID,random_noise
count,3621.0,3621.0,3621.0,3621.0,3621.0,3621.0,3621.0,3621.0,3621.0,3654.0,...,3621.0,3621.0,3621.0,3621.0,3621.0,3621.0,3.511000e+03,3654.0,3654.0,3621.0
mean,983.0,847.0,171.0,1.0,0.0,136.0,350.0,22.0,1.0,1.0,...,632.0,2.0,1813.0,5.0,3724.0,10.0,2.856183e+06,479968.0,10003856.0,-0.0
std,1448.0,1248.0,255.0,5.0,5.0,306.0,581.0,30.0,0.0,0.0,...,1405.0,4.0,2776.0,7.0,4702.0,13.0,5.329956e+07,265234.0,2233.0,1.0
min,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.591150e+05,103940.0,10000000.0,-3.0
25%,181.0,152.0,32.0,0.0,0.0,0.0,44.0,3.0,1.0,1.0,...,0.0,0.0,0.0,1.0,579.0,3.0,1.411000e+03,248016.0,10001894.0,-1.0
50%,493.0,422.0,89.0,0.0,0.0,27.0,148.0,10.0,1.0,1.0,...,0.0,1.0,746.0,3.0,2106.0,5.0,4.553000e+03,475032.0,10003870.0,-0.0
75%,1176.0,1009.0,209.0,0.0,0.0,132.0,427.0,29.0,1.0,1.0,...,684.0,3.0,2463.0,5.0,5155.0,10.0,1.023000e+04,703834.0,10005805.0,1.0
max,21578.0,18128.0,4169.0,181.0,184.0,3795.0,7427.0,423.0,5.0,1.0,...,22297.0,22.0,30235.0,37.0,49747.0,60.0,1.000000e+09,992356.0,10007673.0,3.0

In [12]:
(df[df["repeat_purchase_90d"]==0].describe()).round()

,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,...,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,ID,random_noise
count,2848.0,2848.0,2848.0,2848.0,2848.0,2848.0,2848.0,2848.0,2848.0,2880.0,...,2848.0,2848.0,2848.0,2848.0,2848.0,2848.0,2.763000e+03,2880.0,2880.0,2848.0
mean,763.0,680.0,128.0,1.0,0.0,82.0,300.0,21.0,1.0,0.0,...,235.0,1.0,542.0,1.0,1286.0,3.0,1.812451e+06,540098.0,10003802.0,-0.0
std,1145.0,968.0,179.0,7.0,5.0,265.0,427.0,25.0,0.0,0.0,...,792.0,1.0,1348.0,1.0,2298.0,3.0,4.250878e+07,264473.0,2200.0,1.0
min,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.263800e+04,103940.0,10000003.0,-4.0
25%,171.0,158.0,28.0,0.0,0.0,0.0,57.0,4.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.210000e+02,303976.0,10001927.0,-1.0
50%,390.0,362.0,70.0,0.0,0.0,3.0,158.0,12.0,1.0,0.0,...,0.0,0.0,0.0,1.0,458.0,2.0,1.139000e+03,519184.0,10003774.0,-0.0
75%,859.0,791.0,155.0,0.0,0.0,50.0,366.0,28.0,1.0,0.0,...,0.0,1.0,495.0,2.0,1522.0,4.0,3.108000e+03,792919.0,10005694.0,1.0
max,12500.0,10538.0,2424.0,160.0,218.0,4103.0,4925.0,309.0,5.0,0.0,...,11457.0,9.0,18641.0,22.0,31167.0,57.0,1.000000e+09,998870.0,10007674.0,4.0