In [3]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

import joblib
from IPython.display import display

train_path = os.path.join("..", "data", "raw", "train.csv")
clients_path = os.path.join("..", "data","raw", "clientes.csv")

train_raw = pd.read_csv(train_path, index_col="ID") #tirar o index_col=0, pois estava a fzr o Total a pagar como index
clients_raw = pd.read_csv(clients_path)

In [4]:
print(f"{train_raw.shape[0]:,} rows and {train_raw.shape[1]} columns in the training dataset.")
train_raw.head()

6,534 rows and 38 columns in the training dataset.

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,...,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,random_noise
ID,,,,,,,,,,,,,,,,,,,,,
10000000,558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,...,858.30,660784,Maybe Tomorrow Payment 10,VLOOKUP Master 9,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2024-10-29,-0.660448
10000001,978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,...,2500.68,189146,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 1,2017-07-08,0.924510
10000002,10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,...,7899.80,103940,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,NaN,Final Excel Warehouse 1,Ctrl Z Series 3,2019-03-19,-0.258730
10000003,856.83,696.61,696.61,160.22,0.0,0.0,0.00,408.167275,9.0,1.0,...,270.33,512927,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 71,Final Excel Warehouse 1,Ctrl Z Series 3,2018-11-10,1.448402
10000004,1616.10,1488.85,1313.90,302.20,0.0,0.0,174.95,485.401864,33.0,1.0,...,2062.50,122356,Maybe Tomorrow Payment 12,NaN,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2021-11-30,-1.058890

In [5]:
train_raw.info()
train_raw.dtypes.value_counts()

<class 'pandas.DataFrame'>
Index: 6534 entries, 10000000 to 10007674
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total a Pagar                   6469 non-null   float64
 1   Total Bruto                     6469 non-null   float64
 2   Total Liquido                   6469 non-null   float64
 3   Total Imp_                      6469 non-null   float64
 4   Total Portes                    6469 non-null   float64
 5   Total Desc_ Global              6469 non-null   float64
 6   Total Desc_ Linha               6469 non-null   float64
 7   Custo                           6469 non-null   float64
 8   N_ Detalhes                     6469 non-null   float64
 9   invoice_count_current_purchase  6469 non-null   float64
 10  repeat_purchase_90d             6534 non-null   int64
 11  days_since_previous_purchase    5673 non-null   float64
 12  customer_tenure_days            6469 non-null   float64
 13  prior_purchase_count            6469 non-null   float64
 14  prior_total_spend               6469 non-null   float64
 15  prior_mean_purchase_value       5672 non-null   float64
 16  prior_std_purchase_value        5421 non-null   float64
 17  prior_min_purchase_value        5866 non-null   float64
 18  prior_max_purchase_value        5866 non-null   float64
 19  prior_mean_gap_days             5226 non-null   float64
 20  prior_std_gap_days              5056 non-null   float64
 21  purchase_count_30d              6469 non-null   float64
 22  spend_30d                       6469 non-null   float64
 23  purchase_count_90d              6469 non-null   float64
 24  spend_90d                       6469 non-null   float64
 25  purchase_count_180d             6469 non-null   float64
 26  spend_180d                      6469 non-null   float64
 27  purchase_count_365d             6469 non-null   float64
 28  spend_365d                      6274 non-null   float64
 29  customer_id                     6534 non-null   int64
 30  payment_type                    6274 non-null   str
 31  salesperson                     6275 non-null   str
 32  commercial_zone                 6469 non-null   str
 33  transport_method                6273 non-null   str
 34  warehouse                       6274 non-null   str
 35  document_series                 6469 non-null   str
 36  purchase_date                   6469 non-null   str
 37  random_noise                    6469 non-null   float64
dtypes: float64(29), int64(2), str(7)
memory usage: 1.9 MB

float64    29
str         7
int64       2
Name: count, dtype: int64

In [7]:
train_raw.describe().T

,count,mean,std,min,25%,50%,75%,max
Total a Pagar,6469.0,9.255563e+02,1.334998e+03,0.930000,188.920000,476.740000,1087.670000,2.229721e+04
Total Bruto,6469.0,8.861527e+02,1.327641e+03,0.830000,175.740000,445.740000,1036.700000,2.157828e+04
Total Liquido,6469.0,7.733364e+02,1.136356e+03,0.760000,154.380000,389.910000,903.370000,1.812781e+04
Total Imp_,6469.0,1.522199e+02,2.252624e+02,0.000000,29.930000,79.740000,184.840000,4.169400e+03
Total Portes,6469.0,1.151427e+00,5.844091e+00,0.000000,0.000000,0.000000,0.000000,1.810600e+02
Total Desc_ Global,6469.0,3.499072e-01,5.116564e+00,0.000000,0.000000,0.000000,0.000000,2.184900e+02
Total Desc_ Linha,6469.0,1.124664e+02,2.899863e+02,0.000000,0.000000,13.130000,92.280000,4.103440e+03
Custo,6469.0,3.281650e+02,5.195072e+02,0.000000,49.050000,152.540000,396.061499,7.427401e+03
N_ Detalhes,6469.0,2.152450e+01,2.771342e+01,1.000000,4.000000,11.000000,29.000000,4.230000e+02
invoice_count_current_purchase,6469.0,1.066007e+00,3.108069e-01,1.000000,1.000000,1.000000,1.000000,5.000000e+00
repeat_purchase_90d,6534.0,5.592287e-01,4.965176e-01,0.000000,0.000000,1.000000,1.000000,1.000000e+00
days_since_previous_purchase,5673.0,1.015302e+02,1.657049e+02,-4.000000,17.000000,57.000000,119.000000,3.199000e+03
customer_tenure_days,6469.0,1.111384e+03,9.231908e+02,0.000000,308.000000,918.000000,1759.000000,3.506000e+03
prior_purchase_count,6469.0,2.345788e+01,3.834484e+01,0.000000,3.000000,11.000000,27.000000,2.760000e+02
prior_total_spend,6469.0,1.890835e+04,3.113087e+04,0.000000,1505.550000,6754.310000,21642.320000,2.478651e+05
prior_mean_purchase_value,5672.0,2.821825e+06,5.304157e+07,-2478.658478,359.558125,724.897033,1095.887323,1.000000e+09
prior_std_purchase_value,5421.0,7.374697e+02,6.662619e+02,0.000000,258.560327,569.077581,981.093653,6.770221e+03
prior_min_purchase_value,5866.0,1.854620e+02,4.083986e+02,0.930000,15.450000,64.340000,162.610000,6.298980e+03
prior_max_purchase_value,5866.0,2.946378e+03,5.901548e+03,3.310000,834.530000,1783.240000,3504.420000,2.675262e+05
prior_mean_gap_days,5226.0,9.587666e+01,1.225893e+02,-4.000000,42.596591,68.444444,113.831579,3.199000e+03
prior_std_gap_days,5056.0,7.413544e+01,1.018195e+02,0.000000,32.736068,50.635354,78.626119,2.212537e+03
purchase_count_30d,6469.0,6.005565e-01,1.214975e+00,0.000000,0.000000,0.000000,1.000000,1.100000e+01
spend_30d,6469.0,4.571410e+02,1.191231e+03,0.000000,0.000000,0.000000,338.240000,2.229721e+04
purchase_count_90d,6469.0,1.631937e+00,2.977981e+00,0.000000,0.000000,1.000000,2.000000,2.200000e+01
spend_90d,6469.0,1.253528e+03,2.347842e+03,0.000000,0.000000,198.500000,1514.560000,3.023488e+04
purchase_count_180d,6469.0,3.374556e+00,5.460510e+00,0.000000,1.000000,2.000000,3.000000,3.700000e+01
spend_180d,6469.0,2.650600e+03,4.020267e+03,0.000000,149.160000,1117.680000,3404.440000,4.974697e+04
purchase_count_365d,6469.0,6.561601e+00,1.032554e+01,0.000000,1.000000,3.000000,7.000000,6.000000e+01
spend_365d,6274.0,2.396535e+06,4.884113e+07,-159115.175535,637.782500,2426.605000,7045.422500,1.000000e+09
customer_id,6534.0,5.064719e+05,2.665560e+05,103940.000000,258332.000000,489625.000000,755628.000000,9.988700e+05
random_noise,6469.0,-2.214013e-02,1.001054e+00,-3.529210,-0.677770,-0.045714,0.641711,4.151241e+00

In [ ]:
train_raw["repeat_purchase_90d"].value_counts(normalize=True)*100
train_raw.value_counts(normalize=True).plot(kind="bar", figsize=(8, 5), color="steelblue")

<Axes: xlabel='Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,random_noise'>